### ISSUE TITLE
No functionality for setting a timeout on requests

### ISSUE THREAD

**Issue by GR1ML0CK** [paysafegroup/paysafe_sdk_java#3]
The SDK does not allow for the ability to `setConnectTimeout` or 'setReadTimeout' on the connection that is created by `PaysafeApiClient`. Because all the classes in the sdk heavily use final any private keywords across class properties and methods, the functionality cannot be extended out easily to add these features

**Comment by francoisneron** [comment]
The current SDK does not have a mechanism in place to handle connection timeout, but you could definitely manage/add this by setting one on the http client (e.g HttpURLConnection object) when we fire the request.

https://github.com/paysafegroup/paysafe_sdk_java/blob/master/PaysafeSDK/src/main/java/com/paysafe/PaysafeApiClient.java#L242

https://stackoverflow.com/questions/2799938/httpurlconnection-timeout-settings

**Comment by bozhidarpaysafe** [comment]
Connection timeout and read timeout are added into our PaysafeApiClient
https://github.com/paysafegroup/paysafe_sdk_java/pull/13
