### ISSUE TITLE
Keywords and description not passed in CardPaymentService authorise calls

### ISSUE THREAD

**Issue by richbruin** [paysafegroup/paysafe_sdk_java#8]
It is possible to set a description and keywords on the Authorisation object that you pass to the CardPaymentService authorise() call. However, these fields are not passed in the request body because they lack an @Expose annotation.

**Comment by bozhidarpaysafe** [comment]
Fix is applied with PR: https://github.com/paysafegroup/paysafe_sdk_java/pull/15
